# Generated by Django 4.2.7 on 2023-11-23 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incubatordevice',
            name='unique_id',
            field=models.CharField(default='894ed113-b552-4678-99b0-50df533821a7', editable=False, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
