# Generated by Django 4.2.7 on 2023-11-24 00:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_incubatordevice_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incubatordevice',
            name='unique_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
